apiVersion: v1
kind: Service
metadata:
  name: scraper-service
  labels:
    app: scraper-service
spec:
  selector:
    app: scraper-service
  ports:
  - name: app-port
    port: 8080
    targetPort: 8080
  - name: metrics-port
    port: 9095
    targetPort: 9095
